export const config = {
  newsApiKey: import.meta.env.VITE_NEWS_API_KEY || '',
  groqApiKey: import.meta.env.VITE_GROQ_API_KEY || '',
  geminiApiKey: import.meta.env.VITE_GEMINI_API_KEY || '',
  cerebrasApiKey: import.meta.env.VITE_CEREBRAS_API_KEY || '',
  openrouterApiKey: import.meta.env.VITE_OPENROUTER_API_KEY || '',
  googleClientId: import.meta.env.VITE_GOOGLE_CLIENT_ID || '',
  youtubeApiKey: import.meta.env.VITE_YOUTUBE_API_KEY || '',
  elevenLabsApiKey: import.meta.env.VITE_ELEVENLABS_API_KEY || '',
  twitterClientId: import.meta.env.VITE_TWITTER_CLIENT_ID || '',
  
  get hasNewsApi() { return this.newsApiKey.length > 0; },
  get hasGroq() { return this.groqApiKey.length > 0; },
  get hasGemini() { return this.geminiApiKey.length > 0; },
  get hasCerebras() { return this.cerebrasApiKey.length > 0; },
  get hasOpenRouter() { return this.openrouterApiKey.length > 0; },
  get hasAI() { return this.hasGroq || this.hasCerebras || this.hasGemini || this.hasOpenRouter; },
  get hasGoogleAuth() { return this.googleClientId.length > 0; },
  get hasYoutubeApi() { return this.youtubeApiKey.length > 0; },
  get hasElevenLabs() { return this.elevenLabsApiKey.length > 0; },
};
